environment: production

container:
    name: weather-api
    image: gcr.io/weather-286421/weather.api
    tag: 0.1.0
    port: 8080

label:
    name: weather-api

service:
  port: 8080
  type: LoadBalancer