environment: production

container:
    name: weather-api
    image: gcr.io/weather-286421/weather.api
    tag: 0.1.0
    port: 80
replicas: 1

kubernetesServiceAccount: weather-api-kube-account

label:
    name: weather-api

service:
  port: 80
  type: LoadBalancer