language: csharp
mono: none
dotnet: 3.0.100
services:
  - docker
env:
  global:
    - GCP_PROJECT_ID=weather-286421
    - IMAGE=gcr.io/$GCP_PROJECT_ID/Weather.Api
before_install:
  - openssl aes-256-cbc -K $encrypted_98d237b7dbf4_key -iv $encrypted_98d237b7dbf4_iv -in google-key.json.enc -out google-key.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source "$HOME/google-cloud-sdk/path.bash.inc"
  - gcloud auth activate-service-account --key-file=google-key.json
  - gcloud auth configure-docker   
  - gcloud config set project "${GCP_PROJECT_ID}"
install: true # no-op

deploy:
  - provider: script
    script:
      - docker build -t "${IMAGE}:${TRAVIS_COMMIT}"
      - docker push "${IMAGE}:${TRAVIS_COMMIT}"
    on:
      branch: master
  - provider: script
    script:
      - dotnet restore
      - dotnet build
    on:
      branch: develop