service: weather-api
frameworkVersion: '3'

provider:
  name: aws
  httpApi:
    id: ${ssm:/weather-app/http-api-id}
  ecr:
    images:
      weather-api:
        path: ./
        platform: linux/amd64

resources:
  Resources:
    WeatherApiRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: WeatherApiRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: WeatherApiPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
                - Effect: Allow
                  Action:
                    - ec2:CreateNetworkInterface
                    - ec2:DescribeNetworkInterfaces
                    - ec2:DetachNetworkInterface
                    - ec2:DeleteNetworkInterface
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - secretsmanager:ListSecrets
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - secretsmanager:GetSecretValue
                    - secretsmanager:DescribeSecret
                  Resource:
                    - ${ssm:/weather-app/database-connection-string}
                - Effect: Allow
                  Action:
                    - secretsmanager:PutSecretValue
                    - secretsmanager:CreateSecret
                    - secretsmanager:UpdateSecret
                  Resource: "*"
functions:
  weather-api:
    image:
      name: weather-api
    events:
      - httpApi:
          method: ANY
          path: /api/weather/{proxy+}
    role: WeatherApiRole
    timeout: 300